name: Build VyOS Images
on:
  # Run every Sunday at 00:00
  schedule:
    - cron: '0 0 * * 0'
  # Run when manually triggered
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: ammmze/vyos

jobs:
  rolling-latest:
    name: Rolling Latest
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Packages
        run: sudo apt install -y squashfs-tools

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch ISO
        run: curl -O https://s3.amazonaws.com/s3-us.vyos.io/rolling/current/vyos-rolling-latest.iso

      - name: Build
        run: ./build.sh vyos-rolling-latest.iso ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} rolling-latest

      - name: Push
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:rolling-latest
